[package]
name = "twr"
version = "0.1.0"
edition = "2021"

[dependencies]
tower = { version = "0.5", features = ["util"] }
tokio = { version = "1.44", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"
pin-project = "1.1"
