[package]
name = "chain-game"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
rand = "0.8.5"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }
thiserror = "2.0"
